[31m
exunit_summarizer: 6 tests: 3 passed, 1 skipped, 2 failed[0m
Â Â Failed tests:
Â Â Â Â Elixir.TestWithSummaryTest
Â Â Â Â Â Â [31mtest one that fails when MAKE_TESTS_FAIL != ""[0m
Â Â Â Â Â Â - test/exunit_summarizer_test.exs:13
Â Â Â Â Â Â Â Â [31mAssertion with == failed[0m
Â Â Â Â Â Â Â Â [36mcode:  [0massert @should_fail == ""
Â Â Â Â Â Â Â Â [36mleft:  [0m"[31mthis test intentionally fails[0m"
Â Â Â Â Â Â Â Â [36mright: [0m"[48;5;28m[0m"
Â Â Â Â Â Â Â Â [36mstacktrace:[0m
Â Â Â Â Â Â Â Â   test/exunit_summarizer_test.exs:16: (test)
Â Â Â Â Â Â Â Â [36mlogs:[0m
Â Â Â Â Â Â Â Â Â Â [33m[warn] This should output.
Â Â Â Â Â Â Â Â Â Â [0m[31m[error] This should show an error.[0m
Â Â Â Â Â Â [31mtest a describe block one that fails when MAKE_TESTS_FAIL != ""[0m
Â Â Â Â Â Â - test/exunit_summarizer_test.exs:35
Â Â Â Â Â Â Â Â [31mAssertion with == failed[0m
Â Â Â Â Â Â Â Â [36mcode:  [0massert @should_fail == ""
Â Â Â Â Â Â Â Â [36mleft:  [0m"[31mthis test intentionally fails[0m"
Â Â Â Â Â Â Â Â [36mright: [0m"[48;5;28m[0m"
Â Â Â Â Â Â Â Â [36mstacktrace:[0m
Â Â Â Â Â Â Â Â   test/exunit_summarizer_test.exs:36: (test)
** (Mix) One or more tests in the report failed.
