
exunit_summarizer: 6 tests: 3 passed, 1 skipped, 2 failed
Â Â Failed tests:
Â Â Â Â Elixir.TestWithSummaryTest
Â Â Â Â Â Â test one that fails when MAKE_TESTS_FAIL != ""
Â Â Â Â Â Â - test/exunit_summarizer_test.exs:13
Â Â Â Â Â Â Â Â Assertion with == failed
Â Â Â Â Â Â Â Â code:  assert @should_fail == ""
Â Â Â Â Â Â Â Â left:  "this test intentionally fails"
Â Â Â Â Â Â Â Â right: ""
Â Â Â Â Â Â Â Â stacktrace:
Â Â Â Â Â Â Â Â   test/exunit_summarizer_test.exs:16: (test)
Â Â Â Â Â Â Â Â logs:
Â Â Â Â Â Â Â Â Â Â [33m[warn] This should output.
Â Â Â Â Â Â Â Â Â Â [0m[31m[error] This should show an error.[0m
Â Â Â Â Â Â test a describe block one that fails when MAKE_TESTS_FAIL != ""
Â Â Â Â Â Â - test/exunit_summarizer_test.exs:35
Â Â Â Â Â Â Â Â Assertion with == failed
Â Â Â Â Â Â Â Â code:  assert @should_fail == ""
Â Â Â Â Â Â Â Â left:  "this test intentionally fails"
Â Â Â Â Â Â Â Â right: ""
Â Â Â Â Â Â Â Â stacktrace:
Â Â Â Â Â Â Â Â   test/exunit_summarizer_test.exs:36: (test)
** (Mix) One or more tests in the report failed.
